IDE-33 구독-세션-스토리지 개발 및 퇴장 알림
The-Great-Sign/IDE-Project-backend pull request #16
Opened 2023-12-13 13:21 UTC by leebongseung

변경사항
- ChatsService 
  -  현재 인원 계산하는 로직 추가 
  - enter 메서드시 웹소켓 세션 매퍼에 저장.
  - talk 메서드 호출 시 db 저장 로직
  - exit 메서드 호출 시 
-  ChattingController
   - jwt, 시큐리티나 적용할 부분 우선 todo로 비워둠 방법 고안중
- SubscribeSessionMapper
  - key  : websocketsessionId 와 
  - value : 웹소켓유저정보(websocketsessionId, ProjectId, userId, subscribeType)를 담은 매퍼 만듬.
- WebSocketUserSession
  - sessionId, userId, projectId, subscribeType 을 저장한 객체
- SubscribeType(enum)
  - chatting, terminal, cursor
  - 역할 : 어느 구독 방인지 구분하는 역할 퇴장 알림시에 사용됩니다.
- WebSocketEventListener
  - handleWebSocketDisconnectListener 이벤트 발생 시 퇴장 및 웹소켓유저정보 담은 세션 삭제하기

2023-12-13 13:54 UTC, sbslc2000 requested changes

2023-12-13 13:54 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/SubscribeSessionMapper.java
> +        sessions.put(webSocketSession.getSessionId(), new WebSocketUserSession(webSocketSession.getSessionId(), userId, projectId,subscribeType));
이미 Key에 WebSocketSession의 sessionId가 저장되어있는데 value에 sessionId가 또 저장되는 것은 불필요해 보입니다. 특별한 이유가 있나요?

2023-12-13 13:54 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/SubscribeSessionMapper.java
> +        sessions.put(webSocketSession.getSessionId(), new WebSocketUserSession(webSocketSession.getSessionId(), userId, projectId,subscribeType));
사용자가 하나의 sessionId를 통해 터미널과 채팅과 커서를 구독하게 될 텐데, key를 sessionId를 두면 이후의 구독에 의해서 Map의 값이 덮어씌워질 것 같습니다.

2023-12-13 13:54 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/WebSocketUserSession.java
> +package goorm.dbjj.ide.websocket;
웹소켓 세션 자체에 setAttribute 를 통해 값을 부여할 수 있는 것으로 알고 있습니다. 이 방법을 고려하는 것과 별도의 클래스를 만들어 관리하는 작업 중 장단을 따져서 결정하면 좋을 것 같습니다.

2023-12-13 13:54 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChatsService.java
> +    private final AtomicLong currentUsers; // 현재 유저가 몇명인지 나타내는 변수
이 변수를 유지하는 이유가 무엇인가요? 모든 채팅방을 포함하는 유저의 수를 관리하는 변수로 보입니다.

2023-12-13 13:54 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChatsService.java
> +    @Autowired
@RequiredArgsConstructor로 대체하는 것이 좋아 보입니다.

2023-12-13 13:54 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChatsService.java
> +        if (currentValue < 0) {
일반적인 로직(입장시 enter, 퇴장시 exit)에서 발생하면 안되는 오류이므로 Error 수준의 로그를 출력하는 것이 좋아 보입니다. 메서드명의 첫 글자를 소문자로 해서 전체 컨벤션에 맞게 하면 좋을 것 같습니다.

2023-12-13 13:54 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChatsService.java
> +        projectUsersRepository.find(userId,ProjectId).orElseThrow(() -> new BaseException("없는 프로젝트 입니다.")
이 Validation은 분명 필요해 보입니다. 하지만 너무 잦은 DB 쿼리가 발생할 가능성이 있어 보입니다. 추후의 이슈지만, 필요하다면 캐싱을 통해 DB를 접근하는 과정을 줄일 필요가 있어 보입니다.

2023-12-13 13:54 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChattingController.java
>              @Payload ChattingContentRequestDto chatsDto
이부분 변수명도 클래스에 맞게 수정하면 좋을 것 같습니다.

2023-12-13 13:54 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/SubscribeSessionMapper.java
> +        sessions.put(webSocketSession.getSessionId(), new WebSocketUserSession(webSocketSession.getSessionId(), userId, projectId,subscribeType));
이 부분은 전체 코드의 동작을 망가뜨릴 치명적인 부분이라고 생각합니다. 하나의 웹소켓세션(http://{host}:8080/ws/ide) 연결 내부에 여러 구독 개념이 있다고 알고 있는데 이 부분 확인해주셔야 할 것 같습니다.

2023-12-13 13:55 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChatsService.java
> +    private final AtomicLong currentUsers; // 현재 유저가 몇명인지 나타내는 변수
각각의 채팅방의 참여인원을 표현하기 위한 목적으로는 잘못 사용되는 것으로 보입니다.

2023-12-14 14:13 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChatsService.java
> +        projectUsersRepository.find(userId,ProjectId).orElseThrow(() -> new BaseException("없는 프로젝트 입니다.")
혹시나 Handshake 과정에서 검증할 수 있다면 이후 메시지들에 대해서는 검증하지 않아도 좋을 것 같습니다.

2023-12-15 08:29 UTC, sbslc2000 reviewed
확인 후 반영 부탁드립니다.

2023-12-15 08:29 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/WebSocketEventListener.java
> +        // simpSessionAttributes에 존재하는 uuide 가져오기
오타가 있습니다.

2023-12-15 08:29 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChattingCurrentUserMapper.java
> +    }
getCurrentUsersByProjectId() 정도의 네이밍이 좋을 것 같습니다.

2023-12-15 08:29 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/dto/ChattingResponseDto.java
> +    private Long UserId; // todo : 추후 객체로 전송 해야 함 닉네임 또는 이메일 등
변수명이 카멜케이스로 작성되지 않았습니다.

2023-12-15 08:29 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChattingController.java
> +            @Payload ChattingContentRequestDto chatsDtoChattingContentRequestDto
변수명 확인해주셔야할 것 같습니다.

2023-12-15 08:29 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/model/Chats.java
> +
개인적으로는 클래스명은 Chat으로 가되 @Table(name="Chats")를 통해 DB 컨벤션을 맞추는게 좋지 않나 싶습니다.

2023-12-15 08:29 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/WebSocketChannelInterceptor.java
> +    private String getUUID(StompHeaderAccessor headerAccessor) {
메서드 이름이 명확하게 다가오지 않는다는 느낌을 받습니다.

2023-12-15 08:29 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/chatting/ChattingCurrentUserMapper.java
> +    public void enterProjectCurrentUserMapper(Long projectId){
increase() increaseCurrentUser() increaseCurrentUserWithProjectId() 요런 이름들이 의미적으로 명확할 것 같습니다.

2023-12-16 07:51 UTC, sbslc2000 approved these changes
개선 여지가 있지만 일단 승인합니당

2023-12-16 07:51 UTC, sbslc2000 commented on src/main/java/goorm/dbjj/ide/websocket/WebSocketUser.java
> +    private Boolean isCursor; // false : 구독 안함, true : 구독함
OCP가 잘 지켜지지 않는 형태의 코드로 보입니다.
Set<String>  (혹은 enum을 사용한 Set<SubscriptionType>)을 사용하여

private Set<String> subscribes;

public isSubscibe(String subscribeType)

와 같은 메서드와 필드를 사용하면 확장에도 유연하게 대처할 수 있는 코드가 될 것 같습니다.

2023-12-16 08:46 UTC, leebongseung commented on src/main/java/goorm/dbjj/ide/websocket/WebSocketUser.java
> +    private Boolean isCursor; // false : 구독 안함, true : 구독함
추후 반영하도록 할게요!

2023-12-16 08:46 UTC, merged